module.exports = {
    USER_ID: "user_id",
    USER_NAME: "user_name",
    TOKEN: "token",
    USER_ROLE: "user_role",
    USER_EMAIL: "user_email",
    USER_AVATAR: "user_avatar",
    USER_ADDRESS: "user_address",
    USER_PHONE_NUMBER: "user_phone",
    USER_EVALUE_COUNT:"user_evalue_count",
    USER_FULLNAME:"user_fullname",
    HOUSE_MAX_CUSTOMER:"house_max_customer",
    HOUSE_AVAILABLE_BED:"house_available_bed",
    HOUSE_AVAILABLE_SHOWER:"house_available_shower",
    HOUSE_CATEGORY:"house_category",
    HOUSE_NAME:"house_name",
    HOUSE_ADDRESS:"house_address",
    HOUSE_IMAGES:"house_images",
    HOUSE_AVAILABLE_FROM:"house_available_from",
    HOUSE_AVAILABLE_TO:"house_available_to",
};